name: Main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  code-setup:
    name: Code Setup
    needs: my-job
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: actions/download-artifact@v1

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: my-step
        run: |
          echo "Token ${{ secrets.GITHUB_TOKEN }}"
          echo "Token ${{ secrets.TOKEN }}"
          echo "Hello ${{ github.sha }}"
          echo "Ref ${{ github.ref }}"
          echo "RUN number ${{ github.run_number }}"

      - name: Create Release GITHUB
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
