name: Main
on: push
jobs:
  release-apk:
    name: Release APK
#    needs: version
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
      - run: ./gradlew build

#      - uses: subosito/flutter-action@v1
#        with:
#          channel: 'beta'
#      - run: flutter pub get
#      - run: flutter build apk
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk

      - name: echo
        run: |
          echo "GITHUB_TOKEN ${{ secrets.GITHUB_TOKEN }}"
          echo "Token ${{ secrets.TOKEN }}"
          echo "SHA ${{ github.sha }}"
          echo "Ref ${{ github.ref }}"
          echo "RUN ${{ github.run_number }}"

      - name: Create Release
        id: create_release
        uses: actions/create-artifact@v2.1.4
        with:
          name: APK
          path: build/app/outputs/apk/release/app-release.apk
