name: Main
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"

  code-setup:
    name: Code Setup
    needs: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: my-step
        run: |
          echo "Token ${{ secrets.TOKEN }}"
          echo "Hello ${{ github.sha }}"
          echo "Ref ${{ github.ref }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          token: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
#          commit: ${{ github.sha }}
#          token: ${{ secrets.TOKEN }}


#          artifact: build/app/outputs/apk/release/app-release.apk
#          artifacts: "build/app/outputs/apk/release/*.apk"

#          artifacts: build/app/outputs/apk/release/app-release.apk
#          commit: ${{ github.sha }}
#          token: ${{ secrets.TOKEN }}
